version: "3"
services:
 app:
   container_name: appExpress
   build: .
   command: nodemon --watch . -e js app.js
   ports:
    - "3000:3000"
   volumes:
     - ./app:/var/www
   links:
     - "mongo:mongohost"
 mongo:
   container_name: mongoDB
   image: mongo:latest
   volumes:
     - ./data:/data/db
   ports:
     - '27017:27017'